  <header>
<div class="navbar">
  <div class="navdiv on" id = "hover"><a class="navitem" href="http://localhost/project-krushal-vataliya/index.php?a=grid&c=product">product</a></div>
  <div class="navdiv"><a class="navitem" href="http://localhost/project-krushal-vataliya/index.php?a=grid&c=category">category</a></div>
  <div class="navdiv"><a class="navitem" href="http://localhost/project-krushal-vataliya/index.php?a=grid&c=customer">customer</a></div>
  <div class="navdiv"><a class="navitem" href="http://localhost/project-krushal-vataliya/index.php?a=grid&c=vendor">vendor</a></div>
  <div class="navdiv"><a class="navitem" href="http://localhost/project-krushal-vataliya/index.php?a=grid&c=salesman">salesman</a></div>
  <div class="navdiv"><a class="navitem" href="http://localhost/project-krushal-vataliya/index.php?a=grid&c=shippingmethod">shipping method</a></div>
  <div class="navdiv"><a class="navitem" href="http://localhost/project-krushal-vataliya/index.php?a=grid&c=paymentmethod">payment method</a></div>
</div></header>