<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="Model/Skin/css/style.css">
    <title>product</title>
  </head>
  <body>
    <?php require_once "View/html/header.phtml" ?>
    <div class="flx"><div><h1> add product</h1></div><div><button class="button  "style=" margin-left: 274px;"><a class="add" href="http://localhost/project-krushal-vataliya/index.php?a=grid&c=product">
    Cancel
    </a></button></div> <div class=""><form action="http://localhost/project-krushal-vataliya/index.php?a=insert&c=product" method="POST"><input id="formbutton1" class="formbutton" type="submit" value="Save"></td></div></div>
    <table id="product">
        <tr>
          <th> product_id</th>
          <td><input type="number" id="product_id" name="product[product_id]"></td>
        </tr>
        <tr>
          <th> sku</th>
          <td><input type="text" id="sku" name="product[sku]"></td>
        </tr>
        <tr>
          <th> cost</th>
          <td><input type="number" id="cost" name="product[cost]"></td>
        </tr>
        <tr>
          <th> price</th>
          <td><input type="number" id="price" name="product[price]"></td>
        </tr>
        <tr>
          <th> quantity</th>
          <td><input type="number" id="quantity" name="product[quantity]"></td>
        </tr>
        <tr>
          <th> description</th>
          <td><input type="text" id="description" name="product[description]"></td>
        </tr>
        <tr>
          <th> status</th>
          <td> <select name="product[status]" id="status" >
            <option value="available"name="available">available</option>
            <option value="unavailable"name="unavailable">unavailable</option>
            
          </select> </td>
        </tr>
        <tr>
          <th> color</th>
          <td><select name="product[color]" id="color" >
            <option value="1"name="red">red</option>
            <option value="2"name="green">green</option>
            <option value="3"name="blue">blue</option>
          </select></td>
        </tr>
        <tr>
          <th> material</th>
          <td><input type="text" id="material" name="product[material]"></td>
        </tr>
        <td>
        </form>
      </table>
      <?php require_once "View/html/footer.phtml" ?>
    </body>
  </html>