<?php
$product = $this->getProduct();
?>
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="Model/Skin/css/style.css">
    <title>product</title>
  </head>
  <body>
    <?php require_once "View/html/header.phtml" ?>
    <div class="flx"><div><h1> edit product</h1></div><div><button class="button  "style=" margin-left: 274px;"><a  class="add" href="http://localhost/project-krushal-vataliya/index.php?a=grid&c=product">
    Cancel
    </a></button></div> <div class=""><form action="http://localhost/project-krushal-vataliya/index.php?a=update&c=product" method="POST"><input id="formbutton1" class="formbutton" type="submit" value="Save"></td></div></div>
    <table id="product">
      
      <tr hidden>
        <th> product_id</th>
        <td><input type="number" id="product_id" name="product[product_id]"  value="<?php echo $product['product_id']?>"></td>
      </tr>
      <tr>
        <th> sku</th>
        <td><input type="text" id="sku" name="product[sku]" value="<?php echo $product['sku']?>"></td>
      </tr>
      <tr>
        <th> cost</th>
        <td><input type="number" id="cost" name="product[cost]" value="<?php echo $product['cost']?>"></td>
      </tr>
      <tr>
        <th> price</th>
        <td><input type="number" id="price" name="product[price]" value="<?php echo $product['price']?>"></td>
      </tr>
      <tr>
        <th> quantity</th>
        <td><input type="number" id="quantity" name="product[quantity]" value="<?php echo $product['quantity']?>"></td>
      </tr>
      <tr>
        <th> description</th>
        <td><input type="text" id="description" name="product[description]" value="<?php echo $product['description']?>"></td>
      </tr>
      <tr>
        <th> status</th>
        <td><select name="product[status]" id="status" >
          <option value="available"name="Available">available</option>
          <option value="unavailable"name="unavailable">unavailable</option>
          
        </select></td>
      </tr>
      <tr>
        <th> color</th>
        <td><select name="product[color]" id="color" value="<?php echo $color?>" >
          <option value="red"name="Available">red</option>
          <option value="green"name="unavailable">green</option>
          <option value="blue"name="unavailable">blue</option>
          
        </select></td>
      </tr>
      <tr>
        <th> material</th>
        <td><input type="text" id="material" name="product[material]" value="<?php echo $product['material']?>"></td>
      </tr>
    </form>
    
  </table>
  <?php require_once "View/html/footer.phtml" ?>
</body>
</html>