<?php
$products = $this->getProduct();
?>

<!DOCTYPE html>
<html>
	<head>
		<link rel="stylesheet" href="Model/Skin/css/style.css">
		<title></title>
	</head>
	<body>
		<?php require_once "View/html/header.phtml" ?>
		<div class="flx"><div><h1>product</h1></div><div style="margin-left: 635px;margin-top: 15px;"><button class="button " > <a  class="add" href="http://localhost/new_project/index.php?a=add&c=product">
		add product
	</a></button></div></div>
	<table id="product">
		<tr>
			<th> product_id</th>
			<th> sku</th>
			<th> cost</th>
			<th> price</th>
			<th> quantity</th>
			<th> description</th>
			<th> status</th>
			<th> color</th>
			<th> material</th>
			<th> </th>
			<th> </th>
			<th> </th>
		</tr>
		
		<?php foreach ($products as $product): ?>
		<tr>
			<td><?php echo $product['product_id'] ?></td>
			<td><?php echo $product['sku'] ?></td>
			<td><?php echo $product['cost'] ?></td>
			<td><?php echo $product['price'] ?></td>
			<td><?php echo $product['quantity'] ?></td>
			<td><?php echo $product['description'] ?></td>
			<td><?php echo $product['status'] ?></td>
			<td><?php echo $product['color'] ?></td>
			<td><?php echo $product['material'] ?></td>
			<td><a href="http://localhost/new_project/index.php?a=grid&c=product_media&product_id=<?php echo $product['product_id'] ?>">images</a></td>
			<td><a href="http://localhost/new_project/index.php?a=edit&c=product&product_id=<?php echo $product['product_id'] ?>">edit</a></td>
			<td><a href="http://localhost/new_project/index.php?a=delete&c=product&product_id=<?php echo $product['product_id'] ?>">delete<a></td>
		</tr>
		<?php endforeach; ?>
	</table>
	<?php require_once "View/html/footer.phtml" ?>
</body>
</html>