
<table id="product">
  

<tr hidden>
<th> address_id</th>
<td><input type="number" id="address_id" name="vendor_address[vendor_id]"></td>
</tr>
<tr>
<th> address</th>
<td><input type="text" id="address" name="vendor_address[address]"></td>
</tr>
<tr>
<th> city</th>
<td><input type="text" id="city" name="vendor_address[city]"></td>
</tr>
<tr>
<th> state</th>
<td><input type="text" id="state" name="vendor_address[state]"></td>
</tr>
<tr>
<th> country</th>
<td><input type="text" id="country" name="vendor_address[country]"></td>
</tr>
<tr>
<th> zip_code</th>
<td><input type="number" id="zip_code" name="vendor_address[zip_code]"></td>
</tr>


<td>

 
</table>
