<?php
$request = $this->getRequest();
$id=$request->getParam('vendor_id');
$sql ="SELECT * FROM `vendor_address` WHERE `vendor_id`= $id";
$adapter =$this->getAdapter();
$address =$adapter->fetchrow($sql);
if (!$address) {
throw new Exception("Error Processing Request", 1);
}
?>
<!DOCTYPE html>
<html>
	<head>
		<link rel="stylesheet" href="Model/Skin/css/style.css">
		<title>vendor</title>
	</head>
	<body>
		<?php require_once "View/html/header.phtml" ?>
		<div class="flx"><div><h1>vendor <address></address></h1></div></div>
		<table id="product">
			<tr>
				<th>address id</th>
				<th>address</th>
				<th>city</th>
				<th>state</th>
				<th>country</th>
				<th>zip_code</th>
				<th> </th>
			</tr>
			<tr>
				<td><?php echo $address['address_id'] ?> </td>
				<td><?php echo $address['address'] ?></td>
				<td><?php echo $address['city'] ?></td>
				<td><?php echo $address['state'] ?></td>
				<td><?php echo $address['country'] ?></td>
				<td><?php echo $address['zip_code'] ?></td>
				<td><a href="http://localhost/new_project/index.php?a=edit&c=vendor_address&vendor_id=<?php echo $address['vendor_id'] ?>">edit</a></td>
			</tr>
		</table>
	</body>
	<?php require_once "View/html/footer.phtml" ?>
</html>