<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="Model/Skin/css/style.css">
        <title>payment method</title>
    </head>
    <body>
        <?php require_once "View/html/header.phtml" ?>
        <div class="flx"><div><h1> add payment method</h1></div><div><button class="button  "style=" margin-left: 274px;"><a  class="add" href="http://localhost/new_project/index.php?a=grid&c=paymentmethod">
        Cancel
        </a></button></div> <div class=""><form action="http://localhost/new_project/index.php?a=insert&c=paymentmethod" method="POST"><input id="formbutton1" class="formbutton" type="submit" value="Save"></td></div></div>
        <table id="product">
            <tr>
                <th> payment_method_id</th>
                <td><input type="number" id="payment_method_id" name="payment_method[payment_method_id]"></td>
            </tr>
            <tr>
                <th>name</th>
                <td><input type="text" id="name" name="payment_method[name]"></td>
            </tr>
            <tr>
                <th>status</th>
                <td>
                    <select name="payment_method[status]" id="status">
                        <option value="available"name="available">available</option>
                        <option value="unavailable"name="unavailable">unavailable</option>
                    </select>
                </td>
            </tr>
        </form>
    </table>
    <?php require_once "View/html/footer.phtml" ?>
</body>
</html>