<?php
$payment_method = $this->getPaymentMethod();
?>
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="Model/Skin/css/style.css">
    <title>shiping method</title>
  </head>
  <body>
    <?php require_once "View/html/header.phtml" ?>
    <div class="flx"><div><h1> edit payment method</h1></div><div><button class="button  "style=" margin-left: 274px;"><a  class="add" href="http://localhost/project-krushal-vataliya/index.php?a=grid&c=paymentmethod">
    Cancel
    </a></button></div> <div class=""><form action="http://localhost/project-krushal-vataliya/index.php?a=update&c=paymentmethod" method="POST"><input id="formbutton1" class="formbutton" type="submit" value="Save"></td></div></div>
    <table id="product">
      <form action="update_payment_method.php" method="GET">
        <tr>
          <th>payment_method_id</th>
          <td><input type="text" id="name" name="payment_method[payment_method_id]" value="<?php echo $payment_method['payment_method_id']?>"></td>
        </tr>
        <tr>
          <th>name</th>
          <td><input type="text" id="name" name="payment_method[name]" value="<?php echo $payment_method['name']?>"></td>
        </tr>
        <th> status</th>
        <td> <select name="payment_method[status]" id="status" >
          <option value="available"name="available">available</option>
          <option value="unavailable"name="unavailable">unavailable</option>
          
        </select> </td>
      </tr>
    </form>
    
  </table>
  <?php require_once "View/html/footer.phtml" ?>
</body>
</html>