<table id="product">
	
	<tr hidden>
		<th> address_id</th>
		<td><input type="number" id="address_id" name="customer_address[customer_id]"></td>
	</tr>
	<tr>
		<th> address</th>
		<td><input type="text" id="address" name="customer_address[address]"></td>
	</tr>
	<tr>
		<th> city</th>
		<td><input type="text" id="city" name="customer_address[city]"></td>
	</tr>
	<tr>
		<th> state</th>
		<td><input type="text" id="state" name="customer_address[state]"></td>
	</tr>
	<tr>
		<th> country</th>
		<td><input type="text" id="country" name="customer_address[country]"></td>
	</tr>
	<tr>
		<th> zip_code</th>
		<td><input type="number" id="zip_code" name="customer_address[zip_code]"></td>
	</tr>
	<td>
		
	</table>