<?php
$customers = $this->getcustomer();




?>
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="Model/Skin/css/style.css">
        <title>customer</title>
    </head>
    <body>
        <?php require_once "View/html/header.phtml" ?>
        <div class="flx"><div><h1>customer</h1></div><div style="margin-left: 635px;margin-top: 15px;"><button class="button " > <a  class="add" href="http://localhost/new_project/index.php?a=add&c=customer">
        add customer
    </a></button></div></div>
    <table id="product">
        <tr>
            <th>customer_id</th>
            <th>first_name</th>
            <th>last_name</th>
            <th>email</th>
            <th>gender</th>
            <th>mobile</th>
            <th>status</th>
            <th> </th>
            <th> </th>
            <th> </th>
        </tr>
        <?php foreach ($customers as  $customer):?>
        
        <tr>
            <td><?php echo $customer['customer_id'] ?> </td>
            <td><?php echo $customer['first_name'] ?></td>
            <td><?php echo $customer['last_name'] ?></td>
            <td><?php echo $customer['email'] ?></td>
            <td><?php echo $customer['gender'] ?></td>
            <td><?php echo $customer['mobile'] ?></td>
            <td><?php echo $customer['status'] ?></td>
            <td><a href="http://localhost/new_project/index.php?a=edit&c=customer&customer_id=<?php echo $customer['customer_id'] ?>">edit</a></td>
            <td><a href="http://localhost/new_project/index.php?a=delete&c=customer&customer_id=<?php echo $customer['customer_id'] ?>">delete<a></td>
            <td><a href="http://localhost/new_project/index.php?a=grid&c=customer_address&customer_id=<?php echo $customer['customer_id'] ?>">view address<a></td>
        </tr>
        <?php endforeach; ?>
        
        
        
        
    </table>
</body>
<?php require_once "View/html/footer.phtml" ?>
</html>